# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drift < Formula
  desc "A standalone git diff pager for the terminal."
  homepage "https://github.com/aymanbagabas/drift"
  version "0.0.2"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aymanbagabas/drift/releases/download/v0.0.2/drift_0.0.2_darwin_amd64.tar.gz"
      sha256 "c5762cf10385d9f747b84ddf97497d4c4e5f142540aa50ebecbb502beb265b83"

      define_method(:install) do
        bin.install "drift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aymanbagabas/drift/releases/download/v0.0.2/drift_0.0.2_darwin_arm64.tar.gz"
      sha256 "7ae80f32214b4c3cd51abdd66cf107d039434ad695699eddc7ae1a92ce73c459"

      define_method(:install) do
        bin.install "drift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aymanbagabas/drift/releases/download/v0.0.2/drift_0.0.2_linux_amd64.tar.gz"
      sha256 "44acef8c493e8dc40394fbf588ab63c686d7920f16b2c965557e5e428efa4864"
      define_method(:install) do
        bin.install "drift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aymanbagabas/drift/releases/download/v0.0.2/drift_0.0.2_linux_arm64.tar.gz"
      sha256 "88849b5d955942c0d313094caccd68abd9a8525c24e95aa76e3988475f499cc2"
      define_method(:install) do
        bin.install "drift"
      end
    end
  end

  test do
    system "#{bin}/drift", "--version"
  end
end
