# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shcopy < Formula
  desc "Copy text to clipboard from anywhere using ANSI OSC 52 sequence"
  homepage "https://github.com/aymanbagabas/shcopy"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.3/shcopy_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "33164727984823c26c88539026916a6ae67d414f13f6fe205b7ed47e91b90154"

      def install
        bin.install "shcopy"
        man1.install "manpages/shcopy.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.3/shcopy_0.1.3_Darwin_arm64.tar.gz"
      sha256 "0a7c61b1a7fb6c4a33a1c83c88f260130938f9c2c16808b3eaa77c02530c6e4f"

      def install
        bin.install "shcopy"
        man1.install "manpages/shcopy.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.3/shcopy_0.1.3_linux_x86_64.tar.gz"
      sha256 "3d1337c4c78ee4cb1239e89b318b64d7a6b83b4bee6eacb5b45c148a588d9e61"

      def install
        bin.install "shcopy"
        man1.install "manpages/shcopy.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.3/shcopy_0.1.3_linux_arm64.tar.gz"
      sha256 "b12ecc3674fd0251832f1eceb5c84594ea6765df9a866519934fe107665d0e38"

      def install
        bin.install "shcopy"
        man1.install "manpages/shcopy.1.gz"
      end
    end
  end
end
