# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shcopy < Formula
  desc "Copy text to clipboard from anywhere using ANSI OSC 52 sequence"
  homepage "https://github.com/aymanbagabas/shcopy"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.1/shcopy_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "56ca6709fcdc0e704db488971633db032c6ae9590913ea719e79375acd0b68c3"

      def install
        bin.install "shcopy"
        man1.install "manpages/shcopy.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.1/shcopy_0.1.1_Darwin_arm64.tar.gz"
      sha256 "610af4f694dfcd5d67ae04f815872253ca5204d3831a11e4500d0e321fe9739f"

      def install
        bin.install "shcopy"
        man1.install "manpages/shcopy.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.1/shcopy_0.1.1_linux_armv6.tar.gz"
      sha256 "6f9ed971dfaa4ec1fccc823637e435286152e8eb5199416f9b039198e3156a66"

      def install
        bin.install "shcopy"
        man1.install "manpages/shcopy.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.1/shcopy_0.1.1_linux_x86_64.tar.gz"
      sha256 "99b7aa80e00b61de51d707a3f7215b1db0a5768f664042c8bfb8ee354fe203aa"

      def install
        bin.install "shcopy"
        man1.install "manpages/shcopy.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.1/shcopy_0.1.1_linux_arm64.tar.gz"
      sha256 "acc59c4d011c697e2c49d0ed8752c412b737781c83547da33b7a064193c00125"

      def install
        bin.install "shcopy"
        man1.install "manpages/shcopy.1.gz"
      end
    end
  end
end
