# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shcopy < Formula
  desc "Copy text to clipboard from anywhere using ANSI OSC 52 sequence"
  homepage "https://github.com/aymanbagabas/shcopy"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.1/shcopy_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "7b3abe299c1b5ba33730568ad10cfaa68eacc3b76ca49a4a1faa71a80231de74"

      def install
        bin.install "shcopy"
        man1.install "manpages/shcopy.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.1/shcopy_0.1.1_Darwin_arm64.tar.gz"
      sha256 "3e77d7bbbd9303efadd7211b04d958edca5b6577e175d4fad868a595ba351e0b"

      def install
        bin.install "shcopy"
        man1.install "manpages/shcopy.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.1/shcopy_0.1.1_linux_arm64.tar.gz"
      sha256 "42a76f8f0a4736932f6a902add206dba673a8928cf94b45aaf496aa40dec0ce4"

      def install
        bin.install "shcopy"
        man1.install "manpages/shcopy.1.gz"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.1/shcopy_0.1.1_linux_armv6.tar.gz"
      sha256 "2b6e9251d2c3b1be7cfee1b5d910133f79677d27016329c8943d2190d3f78e0b"

      def install
        bin.install "shcopy"
        man1.install "manpages/shcopy.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aymanbagabas/shcopy/releases/download/v0.1.1/shcopy_0.1.1_linux_x86_64.tar.gz"
      sha256 "ef619085751cce862bb8c84454e34438389795ddfe8899fbc9e827a6088236c8"

      def install
        bin.install "shcopy"
        man1.install "manpages/shcopy.1.gz"
      end
    end
  end
end
